version: "3.7"

services:
  es01:
    image: "docker.elastic.co/elasticsearch/elasticsearch-oss:${ELK_VERSION}"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - "es-data-es01:/usr/share/elasticsearch/data"
    environment:
      node.name: es01
      discovery.seed_hosts: es01,es02
      cluster.initial_master_nodes: es01,es02
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: -Xms256m -Xmx256m
    networks:
      - elk  
    profiles:
      - "es"
      - "all"
    ulimits:
      memlock:
        soft: -1
        hard: -1  
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:9200"]
      retries: 120
      interval: 10s
      timeout: 10s  

  es02:
    image: "docker.elastic.co/elasticsearch/elasticsearch-oss:${ELK_VERSION}"
    ports:
      - "9201:9201"
      - "9301:9301"
    volumes:
      - "es-data-es02:/usr/share/elasticsearch/data"
    environment:
      node.name: es02
      discovery.seed_hosts: es01,es02
      cluster.initial_master_nodes: es01,es02
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: -Xms256m -Xmx256m
    networks:
      - elk  
    profiles:
      - "es"
      - "all"  
    ulimits:
      memlock:
        soft: -1
        hard: -1    
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:9200"]
      retries: 120
      interval: 10s
      timeout: 10s

  kibana:
    image: "docker.elastic.co/kibana/kibana-oss:${ELK_VERSION}"
    depends_on:
      es01:
        condition: service_healthy
      es02:
        condition: service_healthy  
    ports:
      - "5601:5601"
    environment:
      - 'ELASTICSEARCH_HOSTS=["http://es01:9200","http://es02:9200"]'
    networks:
      - elk  
    profiles:
      - "kibana"
      - "all"  
  logstash:
    container_name: logstash
    build:
      context: ./logstash
      dockerfile: Dockerfile
      args:
        - LOGSTASH_VERSION=${LOGSTASH_VERSION}
    profiles:
      - logstash"
      - "all"  
    networks:
      - elk
    environment:
      LS_JAVA_OPTS: "-Xmx500m -Xms500m"
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    volumes:
      - type: bind
        source: ./logstash/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    links:
      - es01    
      - es02
    depends_on:
      es01:
        condition: service_healthy
      es02:
        condition: service_healthy  
volumes:
  es-data-es01:
  es-data-es02:

networks:
  elk: 
    driver: bridge